# Generated by Django 5.2.6 on 2025-10-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0002_alter_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='feedback',
            field=models.TextField(default='Please add feedback', max_length=250),
        ),
    ]
