# Generated by Django 5.2.6 on 2025-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='feedback',
            field=models.TextField(default='Please add feedback', max_length=400),
        ),
    ]
